Skip to content


	•	  In this repository All GitHub ↵  Jump to ↵  
	•	No suggested jump to results 
	•	  In this repository All GitHub ↵  Jump to ↵  
	•	  In this user All GitHub ↵  Jump to ↵  
	•	  In this repository All GitHub ↵  Jump to ↵  
	•	
Dashboard Pull requests Issues Codespaces
Marketplace 
Explore Sponsors Settings ￼ Jeffrey218
Sign out 



New repository Import repository New codespace New gist New organization 
￼ 

Sorry, something went wrong. 




Jeffrey218  /   OpenWrt-CI  /  

Clear Command Palette 
Tip: Type # to search pull requests 
Type ? for help and tips 
Tip: Type # to search issues 
Type ? for help and tips 
Tip: Type # to search discussions 
Type ? for help and tips 
Tip: Type ! to search projects 
Type ? for help and tips 
Tip: Type @ to search teams 
Type ? for help and tips 
Tip: Type @ to search people and organizations 
Type ? for help and tips 
Tip: Type > to activate command mode 
Type ? for help and tips 
Tip: Go to your accessibility settings to change your keyboard shortcuts 
Type ? for help and tips 
Tip: Type author:@me to search your content 
Type ? for help and tips 
Tip: Type is:pr to filter to pull requests 
Type ? for help and tips 
Tip: Type is:issue to filter to issues 
Type ? for help and tips 
Tip: Type is:project to filter to projects 
Type ? for help and tips 
Tip: Type is:open to filter to open content 
Type ? for help and tips 

We’ve encountered an error and some results aren't available at this time. Type a new search or try again later. 
No results matched your search Search for issues and pull requests # Search for issues, pull requests, discussions, and projects # Search for organizations, repositories, and users @ Search for projects ! Search for files / Activate command mode > Search your issues, pull requests, and discussions # author:@me Search your issues, pull requests, and discussions # author:@me Filter to pull requests # is:pr Filter to issues # is:issue Filter to discussions # is:discussion Filter to projects # is:project Filter to open issues, pull requests, and discussions # is:open 

Jeffrey218 / OpenWrt-CI Public 
forked from KFERMercer/OpenWrt-CI 
	•	Pin   
	•	Watch 0  Notifications  Participating and @mentions  Only receive notifications from this repository when participating or @mentioned.   All Activity  Notified of all notifications on this repository.   Ignore  Never be notified.    Custom   Select events you want to be notified of in addition to participating and @mentions.   Get push notifications on iOS or Android.      
	•	Fork 6.1k       
	•	Starred 0        Star 0         

	•	Code 
	•	Pull requests 
	•	Actions 
	•	Projects 
	•	Wiki 
	•	Security 
	•	Insights 
	•	Settings 
More 
	•	
Open in github.dev Open in a new github.dev tab
Permalink
master 
Switch branches/tags 

Branches Tags 

View all branches
Name already in use

A tag already exists with the provided branch name. Many Git commands accept both tag and branch names, so creating this branch may cause unexpected behavior. Are you sure you want to create this branch? 
Cancel Create 
OpenWrt-CI/merge-upstream.yml 
Go to file

	•	Go to file T 
	•	Go to line L 
	•	
	•	Copy path 
	•	Copy permalink 

 
 
Cannot retrieve contributors at this time 
55 lines (44 sloc) 1.21 KB 
Raw Blame 


Edit this file
E
Open in github.dev
.
Open in GitHub Desktop 



	•	Open with Desktop 
	•	View raw 
	•	Copy raw contents 
	•	View blame 
	•	
	•	Edit file 
	•	Open with github.dev 
	•	Delete file 

#

# This is free software, lisence use MIT.

# 

# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>

# 

# <https://github.com/KFERMercer/OpenWrt-CI>

#



name: Merge-upstream



on:

push:

branches: 

- master

schedule:

- cron: 30 19 * * *



jobs:



merge:



runs-on: ubuntu-latest



steps:



- name: Checkout

uses: actions/checkout@v2

with:

ref: master

fetch-depth: 0

lfs: true



- name: Set git identity

run : |

git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

git config --global user.name "github-actions[bot]"



- name: Load upstream commits

run: git pull https://github.com/coolsnowwolf/lede.git --log --no-commit



- name: Apply commit changes

run: |

if [ -f ./.git/MERGE_MSG ]; then

mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message

sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message

sed -i '/^\#.*/d' ./tmp/message

git commit --file="./tmp/message"

else

echo "There is no merge commits."

fi



- name: Push Commits

env:

DOWNSTREAM_BRANCH: master

run: git push origin $DOWNSTREAM_BRANCH

	•	Copy lines 
	•	Copy permalink 
	•	View git blame

Go 
Footer
© 2022 GitHub, Inc. 
Footer navigation
	•	Terms
	•	Privacy
	•	Security
	•	Status
	•	Docs
	•	Contact GitHub
	•	Pricing
	•	API
	•	Training
	•	Blog
	•	About

